### ISSUE TITLE
Construct full state of the form 

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyterhub-fancy-profiles#10]
Currently, form state is *implicitly* stored, by the various components using 'name' to set appropriate values on the textboxes, so they are submitted properly.

This is brittle, and a bit hard to test. It also makes the following two features difficult to build:

1. The start button is enabled / disabled appropriately
2. The form can remember the choices end user has made
3. Unit testing is a bit more difficult

Instead, we should use a reducer + context to construct the state as JSON to be posted in a structured way, and then post it via JS.

**Comment by batpad** [comment]
cc @oliverroick

**Comment by yuvipanda** [comment]
https://github.com/yuvipanda/jupyterhub-fancy-profiles/pull/18 was my attempt at this, but i haven't touched it in a while. Please use it if needed but feel free to totally disregard it too!

**Comment by oliverroick** [comment]
@yuvipanda I think most of this has been addressed. Do you agree? If so we can close the ticket and open additional ones if needed.

**Comment by yuvipanda** [comment]
Yep, let's do that :)
