### ISSUE TITLE
Present indication of loading before form is rendered

### ISSUE THREAD

**Issue by consideRatio** [yuvipanda/jupyterhub-fancy-profiles#27]
While the page is loading, it can take ~seconds to present (something depending on the connection of course). It could be nice to have something basic to indicate something is being loaded.

![loading](https://github.com/yuvipanda/jupyterhub-fancy-profiles/assets/3837114/0d21ad9e-4819-4de9-9d44-58b7a2798bb8)

**Comment by batpad** [comment]
I think in the latest version, it no longer shows the Start Server button until the form is loaded, so this does not seem like as much of a problem.

@consideRatio would you be able to test the latest version (that now supports multiple profiles as well), and say if this is still an issue? If it is, I could look at it with @oliverroick, should be easy-ish to add some Loading if we need to. Thanks!

**Comment by batpad** [comment]
I see this is still an issue when running remotely -- it takes a couple seconds before the profile options are loaded and the form is presented to the user -- until then there is just the "Start" button without the form.

It would be great to add some indicator that something is loading.

@oliverroick do you think you could take this on?

**Comment by batpad** [comment]
This is done - there's now a loading indicator before the form data is loaded. Thanks @oliverroick !
