### ISSUE TITLE
Explicitly determine when jupyterhub-fancy-profiles should be used vs the binderhub UI

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyterhub-fancy-profiles#37]
This project provides *some* similarities to the binderhub UI (as seen on mybinder.org), although it is still quite distinct. We should clearly define when this project should be used, and when the binderhub UI should be used.

**Comment by haroldcampbell** [comment]
Possible tasks
- [ ] Sync convo with Partnership, Product & Eng
- [ ] Report
- [ ] Review by Engineering team
- [ ] Create infrastructure team policy

**Comment by yuvipanda** [comment]
I've a 30min meeting with @Gman0909 on monday to work on this

**Comment by yuvipanda** [comment]
Also have a 30min meeting with @jmunroe today

**Comment by yuvipanda** [comment]
Productive meeting with @jmunroe! I'll synthesize the notes from that along with my next meeting with Giuliano.

**Comment by yuvipanda** [comment]
Raw notes from this meeting: https://hackmd.io/FizaH2SeS8irs62KVouv5w

**Comment by yuvipanda** [comment]
Based on conversation during the 2i2c sprint planning meeting, this '8' task was split into a '5' and a '3', and the '5' has been put in the committed column.

**Comment by yuvipanda** [comment]
I've closed the subtasks with this comment: https://github.com/yuvipanda/jupyterhub-fancy-profiles/issues/47#issuecomment-2177262689.
