### ISSUE TITLE
The 'default' profile should be selected by default

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyterhub-fancy-profiles#39]
The `default` profile should be automatically selected when rendered

<img width="1224" alt="image" src="https://github.com/yuvipanda/jupyterhub-fancy-profiles/assets/30430/978079f5-2f6c-4ca7-96ec-29cb0ca749fe">

**Comment by batpad** [comment]
@yuvipanda thanks for the catch - this should be pretty easy to fix - I can look tomorrow once we hopefully have #41 merged.
