### ISSUE TITLE
Selecting a dropdown choice in a profile should select that profile

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyterhub-fancy-profiles#40]
In 
<img width="1076" alt="image" src="https://github.com/yuvipanda/jupyterhub-fancy-profiles/assets/30430/9d768492-7249-4439-bc69-3d41c6a8a8f8">

if I interact with the dropdown 'image' under the second profile, it should automatically select the profile. Currently, it doesn't and i have to manually select it as well

**Comment by batpad** [comment]
Haa, this is a bit of a tricky UI one, and makes me wonder if using Radio buttons is actually the correct UI for this.

Currently, on the `kubespawner` interface, we do something a bit ugly to get the desired behaviour -- i.e. that if a user clicks on a profile option "anywhere", including selecting a drop-down, it also selects that profile option. We wrap the entire element in the `label` for the `input type=radio`: https://github.com/jupyterhub/kubespawner/blob/main/kubespawner/templates/form.html#L5 

I think I would definitely like to **not** do that here. This will likely be something like an `onClick` handler on the entire profile option to select it if it is unselected, or something like that.

Longer term, I think we should consider the UI around this and see if there's something better than these radio buttons.

@oliverroick I think if we can discuss this and if it doesn't seem too complicated, I'd be happy to take it on.
