### ISSUE TITLE
Align labels with baseline of their form control

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyterhub-fancy-profiles#50]
![image](https://github.com/yuvipanda/jupyterhub-fancy-profiles/assets/30430/399d9dd7-c9e0-48ae-b3bd-e38bff966ac1)

You can see that 'Custom Image' is top aligned with the control for it. These should either be baseline or center aligned with the control

**Comment by oliverroick** [comment]
Closed in #70
