### ISSUE TITLE
build image button clicked re-attempts old image textbox value

### ISSUE THREAD

**Issue by consideRatio** [yuvipanda/jupyterhub-fancy-profiles#61]
I got a build failure so I looked to attempt again, but the old github repository specified was re-used instead of the new one.

![bugreport-fancy-profiles](https://github.com/yuvipanda/jupyterhub-fancy-profiles/assets/3837114/df42eac1-6028-49ab-af71-fb129103f06f)

**Comment by oliverroick** [comment]
@consideRatio I believe this has been fixed in the meantime in https://github.com/yuvipanda/jupyterhub-fancy-profiles/pull/68 Can you confirm, whether the issue still exists for you?

**Comment by consideRatio** [comment]
Resolved!
