### ISSUE TITLE
Terminal is out of alignment before building starts

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyterhub-fancy-profiles#74]
The terminal looks like this when starting:

<img width="1033" alt="image" src="https://github.com/user-attachments/assets/d32a32aa-6828-485e-ae81-b7499da8e1f0">

Note that the label is misaligned.

It does align once the build is started:

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/011cac91-238a-4bf8-ae37-5de8c12e59ad">

**Comment by yuvipanda** [comment]
@oliverroick ya i still see it on the latest mastert
<img width="1148" alt="Screenshot 2024-11-13 at 5 43 32 PM" src="https://github.com/user-attachments/assets/3f2eb15a-a747-4751-b46e-f6f89ef56738">

**Comment by yuvipanda** [comment]
Note this is jupyterhub 4, so without the #72 applied

**Comment by oliverroick** [comment]
Resolved in #91
